---
# handlers file for roles/vrf-debian

- name: reboot_host
  reboot:
    msg: "reboot initiated by ansible"
    connect_timeout: 5
    reboot_timeout: 180
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami

